### PR TITLE
Replace data_to_xspline and data_to_unit_curve with data_to_alluvium

### LINKED ISSUE #86: ggalluvial:::data_to_xspline() throws an error when data arg has less than 2 rows.
### Description of the issue

ggalluvial:::data_to_xspline() throws an error when data arg has less than 2 rows.

### Reproducible example

Using the example on the "Tooltips" vignette, if you slice the data arg to only have 1 row, then it doesnt work.

E.g., `ggalluvial:::data_to_xspline(groups_to_draw[[1]][1,], knot.prop = T)` will throw the error "Error in rep(4, nrow(data) - 2) : invalid 'times' argument"

### PR DESCRIPTION
**Pull request by qdread**
Resolves #86  .

Summary of proposed changes:
- Combine data_to_xspline and data_to_unit_curve code into a single, exported function
- Previously the one-row data case was dealt with in geom_alluvium directly. Now it is also dealt with inside data_to_alluvium
- Default arguments are provided to data_to_alluvium, though they are sometimes ignored.
- The shiny apps and vignette describing them were updated to use `data_to_alluvium` instead of the former `ggalluvial:::data_to_xspline`.

This doesn't resolve the potential graphics bug on Windows with R 4.1.1 but I am hoping that will be ironed out in future R builds. If this PR is accepted, I can deploy the edited shiny apps with the corrected code to shinyapps.io.

### CODE REVIEW

**Comment by corybrunson** [comment]
@qdread the all-purpose data-to-alluvium function makes eminent sense, both for internal use and for export. In particular, users can directly inspect all of the source code because this function does not call more specific sub-functions.

I see a few minor needed changes:
* Write documentation for `data_to_alluvium()`.
* Add (only very basic) unit tests for `data_to_alluvium()`.
* Update references to discontinued `data_to_*()` functions in the Shiny vignette.

If you prefer, i can work on these and submit a counter-PR (or is there a proper term for that?). Or, if you make these changes, then i can merge this PR directly.

Are the builds failing only due to the Shiny code? I'm not so worried about that, since we've handled it on `main` before.

Thank you for this fix!!

**Comment by qdread** [comment]
Hey Cory, I am not sure why the builds are failing. There are a number of warnings thrown by the `R CMD check` which don't seem to have anything to do with any changes I made (I think). Things like a warning for using `alpha` with a discrete variable. Maybe they are warnings thrown by the new version of ggplot2? In which case that's annoying.

I think I already updated the references to `data_to_alluvium` in the Shiny vignette. So we can check off item 3 on your checklist. If you don't mind taking care of the other stuff that would be great -- I don't want to mess up your system of documentation and unit testing. You can add commits to this PR before merging. That said I can do it if you need me to.

**Comment by corybrunson** [comment]
@qdread sure, that works! I should have it done this week, or at least have questions regarding whatever isn't.

**Comment by corybrunson** [comment]
@qdread i followed your lead and combined the flow calculators as well. Instead of separate documentation, i included them with their respective geoms. (Also, the residual mentions of the old calculators i thought were in the Shiny vignette were actually just in the not-yet-updated website pages.) If it looks OK to you, then i'll merge the PR.

**Comment by qdread** [comment]
Looks great! Once it's merged, I will redeploy the Shiny apps with the new code (although it will not change their appearance or function in any way, it will be good to keep things consistent).

**Comment by qdread** [comment]
Apps updated 😀

**Pull request merged**
